# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories true

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "D:/Xilinx_projects/project_1/project_1.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "d:/Xilinx_projects/project_1/project_1.srcs/sources_1/ip/c_addsub_v11_0_0/coregen.cgc"

set ipFile "d:/Xilinx_projects/project_1/project_1.srcs/sources_1/ip/c_addsub_v11_0_0/c_addsub_v11_0_0.xco"

set ipName "c_addsub_v11_0_0"

set vlnv "xilinx.com:ip:c_addsub:11.0"

set cgPartSpec "xc7k70t-2fbg484"

set bomFilePath "d:/Xilinx_projects/project_1/project_1.srcs/sources_1/ip/c_addsub_v11_0_0/pa_cg_bom.xml"

set hdlType "Verilog"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

